kind = "web"
previewPath = "/"
title = "Adcker"
version = "1.0.0"
id = "artifacts/adcker"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22014

[services.development]
run = "pnpm --filter @workspace/adcker run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/adcker", "run", "build" ]
publicDir = "artifacts/adcker/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22014"
BASE_PATH = "/"
